Repository csesoc/csesoc.unsw.edu.au, pull requests merged in 2019-10, with the labels that each got.

#18 Add base image
  .browserslistrc
  .editorconfig
  .eslintrc.js
  .gitignore
  LICENSE
  babel.config.js
  docker-compose.yml
  package.json
  postcss.config.js
  public/favicon.ico
  public/index.html
  server/go.mod
  server/go.sum
  server/server.go
  services/api.Dockerfile
  services/db.Dockerfile
  services/server.Dockerfile
  src/App.vue
  src/assets/logo.png
  src/assets/logo.svg
  src/components/HomeGreeting.vue
  src/main.js
  src/plugins/vuetify.js
  src/router.js
  src/views/About.vue
  src/views/Home.vue
  yarn.lock
Labels: point:5, t:feature

#19 Fix missing home greeting component
  src/views/Home.vue
Labels: point:1, t:bug

#20 add grid component
  .eslintrc.js
  public/favicon.ico
  public/index.html
  src/components/NavGrid.vue
  src/views/Home.vue
Labels: point:3, t:feature

#21 add footer component
  src/components/Footer.vue
Labels: point:3, t:feature

#22 add slider component
  src/components/Slider.vue
Labels: point:2, t:feature

#23 Feat/footer
  src/components/Footer.vue
Labels: point:1
