Repository csesoc/csesoc.unsw.edu.au, pull requests merged in 2020-10, with the labels that each got.

#141 Add fonts to static dist files to be searched by server.
  backend/main.go
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#142 Update README.md
  README.md
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#143 CW-231 Refactor Data
  frontend/src/views/Home/Home.vue
  frontend/src/views/Home/Mission.vue
  frontend/src/views/Home/Showcase.vue
  frontend/src/views/Home/Slideshow.vue
  frontend/src/views/Home/StudentResources.vue
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#145 CW-247 Fix event display on homepage
  backend/static/events.json
  frontend/src/components/Event.vue
Labels: Priority: Low, Status: Review Needed, Type: Bug
