Repository csesoc/csesoc.unsw.edu.au, pull requests merged in 2020-08, with the labels that each got.

#82 CW-165 Frontend Testing
  frontend/cypress.json
  frontend/cypress/fixtures/example.json
  frontend/cypress/integration/components/preview.spec.js
  frontend/cypress/plugins/index.js
  frontend/cypress/support/commands.js
  frontend/cypress/support/index.js
  frontend/jest.config.js
  frontend/package.json
  frontend/src/components/Preview.vue
  frontend/src/main.js
  frontend/tests/setup.js
  frontend/tests/unit/preview.spec.js
  frontend/yarn.lock
Labels: Priority: High, Status: Accepted, Type: Enhancement

#83 CW-165 Update README.md
  README.md
Labels: Priority: Low, Status: Accepted, Type: Maintenance

#84 CW-173 Update all dependencies
  frontend/babel.config.js
  frontend/package.json
  frontend/postcss.config.js
  frontend/yarn.lock
Labels: Priority: Low, Status: In Progress, Status: Review Needed, Type: Maintenance

#86 CW-173 Eslint Errors
  frontend/.eslintrc.js
  frontend/src/App.vue
  frontend/src/components/EnquiryForm.vue
  frontend/src/components/EventGrid.vue
  frontend/src/components/FeedbackForm.vue
  frontend/src/components/Footer.vue
  frontend/src/components/HeaderTitle.vue
  frontend/src/components/InfiniteSlideshow.vue
  frontend/src/components/Menu.vue
  frontend/src/components/Preview.vue
  frontend/src/components/SponsorModal.vue
  frontend/src/main.js
  frontend/src/plugins/router.js
  frontend/src/utils/APIClient.js
  frontend/src/utils/Constants.js
  frontend/src/views/About.vue
  frontend/src/views/Engage.vue
  frontend/src/views/Home.vue
  frontend/src/views/Sponsor.vue
Labels: Priority: Critical, Status: Accepted, Type: Maintenance

#89 CW-175 Cypress linting
  frontend/.eslintrc.js
  frontend/cypress/integration/components/preview.spec.js
  frontend/package.json
  frontend/yarn.lock
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#91 CW-173 Spacing SCSS
  frontend/src/styles/abstracts/_mixins.scss
  frontend/src/styles/abstracts/mixins/_breakpoint.scss
  frontend/src/styles/abstracts/mixins/_center.scss
  frontend/src/styles/abstracts/mixins/_clearfix.scss
  frontend/src/styles/abstracts/mixins/_grid_mixin.scss
  frontend/src/styles/abstracts/mixins/_spacing_mixin.scss
  frontend/src/styles/base/_spacing.scss
  frontend/src/styles/base/_typography.scss
  frontend/src/styles/global.scss
Labels: Priority: High, Status: Accepted, Type: Enhancement

#92 CW-173 Colour SCSS
  frontend/src/styles/abstracts/_mixins.scss
  frontend/src/styles/abstracts/mixins/_linear-gradient.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#90 CW-176 Merge form components
  frontend/package.json
  frontend/src/components/EnquiryForm.vue
  frontend/src/components/FeedbackForm.vue
  frontend/src/components/MailingForm.vue
  frontend/src/views/Engage.vue
  frontend/src/views/Sponsor.vue
  frontend/yarn.lock
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#93 CW-173 CW-182 Grid and Spacing Adjustments
  frontend/src/styles/abstracts/_variables.scss
  frontend/src/styles/layout/_grid.scss
  frontend/src/views/Resources.vue
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#80 CW-159 - Front page (bottom half)
  frontend/src/assets/discord_logo.png
  frontend/src/assets/facebook_logo.png
  frontend/src/assets/slack_logo.png
  frontend/src/components/CommunityLink.vue
  frontend/src/views/Home.vue
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#95 CW-173 Icon SCSS
  frontend/src/styles/components/_icons.scss
  frontend/src/styles/global.scss
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#99 CW-178 Infinite slideshow testing
  frontend/cypress/integration/components/infiniteSlideshow.spec.js
  frontend/src/components/InfiniteSlideshow.vue
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#100 CW-202 Update Engage forms
  frontend/cypress/integration/components/mailingForm.spec.js
  frontend/src/components/MailingForm.vue
  frontend/src/views/Engage.vue
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#101 Extend JWT
  backend/server/constants.go
Labels: Priority: Critical, Status: Review Needed, Type: Maintenance

#102 CW-200 FAQ Actions Debug
  backend/server/faq/faq_test.go
Labels: Priority: Critical, Status: Review Needed, Type: Maintenance

#105 CW-173 Button Typography
  frontend/src/styles/abstracts/_variables.scss
  frontend/src/styles/components/_buttons.scss
Labels: Priority: Low, Status: In Progress, Type: Bug

#107 Update events.go to read the Facebook token from .env
  backend/server/constants.go
  backend/server/events/events.go
  backend/static/events.json
  docker-compose.yml
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#104 CW-201 Cypress Testing
  .github/workflows/ci.yml
  frontend/cypress/integration/components/preview.spec.js
  frontend/package.json
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#106 CW-203 Menu redesign
  frontend/src/assets/close-icon.svg
  frontend/src/assets/csesoc-logo-white.svg
  frontend/src/assets/moon-icon.png
  frontend/src/components/Menu.vue
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement
