Repository csesoc/csesoc.unsw.edu.au, pull requests merged in 2020-09, with the labels that each got.

#110 CW-213 SVG loading issue on Firefox
  frontend/src/components/Menu.vue
Labels: Priority: Critical, Status: Review Needed, Type: Bug

#111 CW-214 Menu nitpicks
  frontend/src/components/Menu.vue
Labels: Priority: High, Status: Review Needed, Type: Bug

#108 feat/home page
  frontend/cypress/integration/components/communityLinks.spec.js
  frontend/cypress/support/assertions.js
  frontend/cypress/support/index.js
  frontend/src/components/CommunityLink.vue
  frontend/src/views/Home.vue
Labels: Priority: Low, Status: In Progress, Type: Enhancement

#112 CW-212 Match CSS spacing to design guidelines
  frontend/src/components/Menu.vue
  frontend/src/styles/base/_spacing.scss
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#115 CW-209 CW-211 : Landing page showcase and mission
  frontend/cypress/integration/components/communityLinks.spec.js
  frontend/cypress/integration/components/showcase.spec.js
  frontend/src/assets/landingPageHeaderBackground.png
  frontend/src/assets/mission.jpg
  frontend/src/assets/tmp_chain.png
  frontend/src/styles/base/_typography.scss
  frontend/src/styles/components/_buttons.scss
  frontend/src/views/Home.vue
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#117 CW-155 Footer redesign
  frontend/src/components/Footer.vue
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#116 CW-190 Footer Testing
  frontend/cypress/integration/components/footer.spec.js
  frontend/package.json
  frontend/src/components/Footer.vue
  frontend/src/styles/abstracts/_variables.scss
  frontend/src/styles/components/_buttons.scss
  frontend/yarn.lock
Labels: Priority: High, Status: In Progress, Type: Maintenance

#119 CW-208 : Landing Page Sponsor
  frontend/src/assets/share.svg
  frontend/src/assets/supportusbackground.png
  frontend/src/assets/trophy.svg
  frontend/src/styles/components/_buttons.scss
  frontend/src/views/Home.vue
Labels: Priority: High, Status: Accepted, Type: Enhancement

#120 CW-225 : Landing Page Join Us
  frontend/cypress/integration/components/communityLinks.spec.js
  frontend/src/components/CommunityLink.vue
  frontend/src/views/Home.vue
Labels: Priority: High, Status: Accepted, Type: Enhancement

#118 CW-206 Event design
  frontend/src/components/Event.vue
  frontend/src/components/EventDisplay.vue
  frontend/src/components/EventGrid.vue
  frontend/src/views/Home.vue
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#122 CW-207 Landing page resources
  frontend/src/assets/resource-first-year-guide.png
  frontend/src/assets/resource-job-board.png
  frontend/src/assets/resource-media.png
  frontend/src/assets/resource-notangles.png
  frontend/src/views/Home.vue
Labels: Priority: Critical, Status: Review Needed, Type: Enhancement

#123 CW-191 Landing page events frontend tests
  frontend/cypress/integration/components/landingPageEvents.spec.js
  frontend/src/components/EventDisplay.vue
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#124 CW-226 Wording fixes
  backend/static/social.json
  frontend/src/components/CommunityLink.vue
  frontend/src/components/Footer.vue
  frontend/src/components/Menu.vue
  frontend/src/views/About.vue
  frontend/src/views/Engage.vue
  frontend/src/views/Home.vue
Labels: Priority: Low, Status: Accepted, Type: Maintenance

#125 CW-223 Resources testing
  frontend/cypress/integration/components/resources.spec.js
  frontend/src/views/Home.vue
Labels: Priority: High, Status: Accepted, Type: Enhancement

#126 CW-205 Menu testing
  frontend/cypress/integration/components/menu.spec.js
  frontend/src/App.vue
  frontend/src/components/Menu.vue
Labels: Priority: High, Status: Accepted, Type: Enhancement

#130 CW-229 Make sponsor logos interactive on hover
  frontend/src/views/Sponsor.vue
Labels: Priority: Low, Status: Review Needed

#131 Re-introducing FAQ Tests
  backend/server/faq/faq_test.go
Labels: Priority: Critical, Status: Accepted, Type: Bug

#121 CW-224 Living style guide
  .gitignore
  frontend/.eslintrc.js
  frontend/cypress/integration/components/communityLinks.spec.js
  frontend/cypress/integration/components/footer.spec.js
  frontend/kss-config.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/CommunityLink.vue
  frontend/src/components/EventDisplay.vue
  frontend/src/components/Footer.vue
  frontend/src/components/HeaderTitle.vue
  frontend/src/plugins/router.js
  frontend/src/styles/abstracts/_colours.scss
  frontend/src/styles/abstracts/_variables.scss
  frontend/src/styles/base/_reset.scss
  frontend/src/styles/base/_typography.scss
  frontend/src/styles/components/_buttons.scss
  frontend/src/styles/components/_content.scss
  frontend/src/styles/components/_icons.scss
  frontend/src/styles/global.css
  frontend/src/styles/global.css.map
  frontend/src/styles/global.scss
  frontend/src/styles/layout/_grid.scss
  frontend/src/views/Home.vue
  frontend/src/views/Home/CommunityLink.vue
  frontend/src/views/Home/EventDisplay.vue
  frontend/src/views/Home/Home.vue
  frontend/src/views/Home/Mission.vue
  frontend/src/views/Home/Showcase.vue
  frontend/src/views/Home/Slideshow.vue
  frontend/src/views/Home/SponsorUs.vue
  frontend/src/views/Home/StudentResources.vue
  frontend/src/views/Resources.vue
  frontend/yarn.lock
Labels: Priority: Critical, Status: Review Needed, Type: Enhancement, dependencies

#132 CW-235 Disable Swagger for deployment
  backend/main.go
Labels: Priority: High, Status: Review Needed, Type: Maintenance

#133 CW-230 Dockerfiles for Production
  .dockerignore
  Dockerfile
  backend/main.go
  docker-compose.prod.yml
  frontend/src/components/MailingForm.vue
  frontend/src/main.js
Labels: Priority: High, Status: Review Needed, Type: Maintenance

#134 CW-242 Engage form switch
  frontend/src/components/MailingForm.vue
  frontend/src/views/Engage.vue
Labels: Priority: High, Status: Review Needed, Type: Bug

#135 CW-96 Restructure Database to become more generic
  backend/docs/docs.go
  backend/docs/swagger.json
  backend/docs/swagger.yaml
  backend/main.go
  backend/server/faq/faq.go
  backend/server/resources/resources.go
  backend/server/social/social.go
  backend/static/social.json
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#137 CW-138 Docker Security
  .dockerignore
  Dockerfile
  docker-compose.prod.yml
Labels: Priority: Critical, Status: Review Needed, Type: Maintenance

#128 CW-228 Removing JWT secrets
  .github/workflows/ci.yml
  backend/server/constants.go
  docker-compose.yml
Labels: Priority: Medium, Status: Accepted, Type: Maintenance

#139 CW-245 Duplicate database keys
  backend/server/faq/faq.go
  backend/server/social/social.go
Labels: Priority: High, Status: Review Needed, Type: Bug

#138 CW-244 Move mailing constants
  backend/server/constants.go
  backend/server/mailing/mailing.go
Labels: Priority: High, Status: Review Needed, Type: Enhancement
